### PR TITLE
Fix root prefix init

### PR DESCRIPTION
**Pull request by pavelzw**
Since micromamba 1.4.5, https://github.com/mamba-org/mamba/issues/2442 is solved.

### CODE REVIEW

**Comment by jonashaag** [comment]
This means we can't use old versions of Mamba though

**Comment by pavelzw** [comment]
We could still use versions < 1.4.5 but only with `init-shell: none`.

**Comment by pavelzw** [comment]
But yes, before we release this version we should probably add a warning or something like that...

**Comment by jonashaag** [comment]
It is a breaking change so warrants a major version update. Or we could make the code backwards compatible.

**Pull request merged**
