### PR TITLE
Add specifics about environment creation prereqs

### LINKED ISSUE #72: create-args doesn't work without environment-name
Thanks so much for this great action!

I wanted to share some confusion I had while getting started. 

I figured that there would be a default environment name like `base` and so I didn't set `environment-name`, and then I tried to use `create-args`. This led to no environment being created.

Also, I tried setting `environment-name: base` but that led to

```
error    libmamba Overwriting root prefix is not permitted
```

My feeling is that something is missing from the documentation.

### PR DESCRIPTION
**Pull request by maresb**
Explain in more detail what's needed to create an environment.

Closes #72.

I'm not sure how accurate or fitting this is, so please feel free to disregard this and start from scratch.

### CODE REVIEW

**Review by pavelzw — APPROVED** [review]
Sounds good, thanks!

**Comment by maresb** [comment]
Note how I deleted `environment-specs` because I couldn't find any info about it. My understanding is "environment specs" = `create-args` + `environment-name`.

**Comment by pavelzw** [comment]
I actually don't know where `environment-specs` came from 😅 I wrote the documentation at the end where the API was already set... Maybe GitHub Copilot suggested it 😄

**Comment by jonashaag** [comment]
Does base a special meaning in Micromamba? 🤔

**Comment by maresb** [comment]
Apparently yes, since it seems to denote the root prefix. See #72.

**Pull request merged**
